version: "3.7"

networks:
  default:
    name: autotests-network

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      #- "4442:4442"
      #- "4443:4443"
      - "4444:4444"
    environment:
       GRID_MAX_SESSION: 18
       GRID_BROWSER_TIMEOUT: 3000
       GRID_TIMEOUT: 3000


  chrome:
    image: selenium/node-chrome-debug:latest
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4444
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4444
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    links:
      - selenium-hub
    privileged: true

#here goes all the rest chrome images, necessary for big projects
#do not forget to open on different ports
  chrome_one:
    image: selenium/node-chrome-debug:latest
    container_name: chrome-one
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4444
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4444
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5901"
    links:
      - selenium-hub
    privileged: true

  chrome_two:
    image: selenium/node-chrome-debug:latest
    container_name: chrome-two
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4444
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4444
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5902:5902"
    links:
      - selenium-hub
    privileged: true
    
  chrome_three:
    image: selenium/node-chrome-debug:latest
    container_name: chrome-three
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4444
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4444
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5903:5903"
    links:
      - selenium-hub
    privileged: true